### PR TITLE
Update SMK and other updates to match smk-fap-fcb

### PR DESCRIPTION
**Pull request by dgboss**
link to demo deployment of your smk based app is 
 https://smk-fap-bcfls-rt-b16795-dev.apps.silver.devops.gov.bc.ca

Verify that it looks good, if so merge the pull request which will trigger a prod deployment, otherwise close the pull request without merging

 mentions / notifications: @GuyTheFlower, @NicoledeGreef, @franTarkenton

### CODE REVIEW

**Comment by franTarkenton** [comment]
The Vanity URL for the dev deploy is https://smk-fap-bcfls-api-gov-bc-ca.test.api.gov.bc.ca
 

If this is a dev deploy,  verify that it looks good, then merge the pull request to trigger prod deployment.

 If this is a prod deployment, view your prod deploy at the url above :)

 mentions / notifications: @GuyTheFlower, @NicoledeGreef, @franTarkenton

**Comment by NicoledeGreef** [comment]
Looks good but it would be great to adjust the British Columbia logo size.  It is a bit stretched at the moment, the french app https://smk-fap-fcb-api-gov-bc-ca.test.api.gov.bc.ca/ looks rightsized.

**Comment by dgboss** [comment]
Oh yes, the logo is another to do. The image we have is very low resolution and we actually have to expand it to get the space to fill. Do you know of a source for a better quality image?

**Comment by NicoledeGreef** [comment]
You can peruse and download all the official Province of BC marks here: https://www2.gov.bc.ca/gov/content/governments/services-for-government/policies-procedures/bc-visual-identity/download-marks
the one you want is under "Main BC Mark"

**Comment by dgboss** [comment]
Something is broken and I can't re-run the build pipeline in this PR. I'm going to close this PR and create a new one so we get a new image built and deployed.

**Comment by franTarkenton** [comment]
The Vanity URL for the dev deploy is https://smk-fap-bcfls-api-gov-bc-ca.test.api.gov.bc.ca
 

If this is a dev deploy,  verify that it looks good, then merge the pull request to trigger prod deployment.

 If this is a prod deployment, view your prod deploy at the url above :)

 mentions / notifications: @GuyTheFlower, @NicoledeGreef, @franTarkenton

**Comment by dgboss** [comment]
@NicoledeGreef, the logo has been updated with a higher resolution image and re-sized properly.

**Comment by NicoledeGreef** [comment]
looks great, @dgboss.  thanks!

**Comment by franTarkenton** [comment]
link to demo deployment of your smk based app is 
 https://smk-fap-bcfls-rt-b16795-prod.apps.silver.devops.gov.bc.ca

Verify that it looks good, if so merge the pull request which will trigger a prod deployment, otherwise close the pull request without merging

 mentions / notifications: @GuyTheFlower, @NicoledeGreef, @franTarkenton

**Comment by franTarkenton** [comment]
The Vanity URL for the prod deploy is https://smk-fap-bcfls.api.gov.bc.ca
 

If this is a dev deploy,  verify that it looks good, then merge the pull request to trigger prod deployment.

 If this is a prod deployment, view your prod deploy at the url above :)

 mentions / notifications: @GuyTheFlower, @NicoledeGreef, @franTarkenton

**Pull request merged**
